### ISSUE TITLE
Add travis build example

### ISSUE THREAD

**Issue by razzeee** [danneu/generator-elm#12]
Are you willing to also accept a travis example, had to bite my nails for some days to even get that to work. So it would probably be nice to at least have it in the readme.

**Comment by danneu** [comment]
@Razzeee I'm open to any pull requests! It's been a while since I used Elm and I tend to update this generator every time I revisit Elm, so it kinda stagnates between my Elm work sessions.

**Comment by razzeee** [comment]
Okay, will prepare it as soon as I find the time.
